import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Metadata } from "next";
import AuthGate from "@/components/auth-gate";
import AppProvider from "./app-provider";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster position="bottom-right" richColors />
        <AppProvider>
          <AuthGate>{children}</AuthGate>
        </AppProvider>
      </body>
    </html>
  );
}

